{{- if .Values.klustairfrontend.enabled -}}
{{- $fullName := include "klustair.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "klustair.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.klustairfrontend.url }}
    secretName: {{ .Values.klustairfrontend.url }}-secret
{{- end }}
  rules:
  - host: {{ .Values.klustairfrontend.url }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        {{- end }}
        backend:
        {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "klustair.fullname" . }}-frontend
            port:
              number: {{ $svcPort }}
        {{- else }}
          serviceName: {{ include "klustair.fullname" . }}-frontend
          servicePort: {{ $svcPort }}
        {{- end }}
{{- end -}}