{{- if .Values.klustairJob.enabled -}}
{{- if eq .Values.phase "prd" -}}
apiVersion: batch/v1beta1
{{- else -}}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "klustair.fullname" . }}-job
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.klustairJob.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- if .Values.klustairJob.podLabels }}
            {{- toYaml .Values.klustairJob.podLabels | nindent 12 }}
            {{- end }}
        spec:
          containers:
          - name: {{ .Chart.Name }}-runnerjob
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsUser: 1000
              runAsGroup: 1000
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - klustair-cli
              - --verbose
              {{- if .Values.trivy.enabled }}
              - -t
              {{- end }}
            env:
              - name: KUBECONFIG
                value: /etc/klustair/kube.config
              - name: KLUSTAIR_APITOKEN
                value: {{ .Values.klustairfrontend.apiToken | default "not_set" | quote}}
              {{ if .Values.klustairJob.label -}}
              - name: KLUSTAIR_LABEL
                value: {{ .Values.klustairJob.label | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.kubeaudit -}}
              - name: KLUSTAIR_KUBEAUDIT
                value: {{ .Values.klustairJob.kubeaudit | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.apiHost -}}
              - name: KLUSTAIR_APIHOST
                value: {{ .Values.klustairJob.apiHost | quote}}
              {{ else }}
              - name: KLUSTAIR_APIHOST
                value: "http://{{ include "klustair.fullname" . }}-frontend"
              {{ end -}}
              {{ if .Values.klustairJob.configKey -}}
              - name: KLUSTAIR_CONFIGKEY
                value: {{ .Values.klustairJob.configKey | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.namespaces -}}
              - name: KLUSTAIR_NAMESPACES
                value: {{ .Values.klustairJob.namespaces | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.namespaceblacklist -}}
              - name: KLUSTAIR_NAMESPACESBLACKLIST
                value: {{ .Values.klustairJob.namespaceblacklist | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.limitDate -}}
              - name: KLUSTAIR_LIMITDATE
                value: {{ .Values.klustairJob.limitDate | quote}}
              {{ end -}}
              {{ if .Values.klustairJob.limitNR -}}
              - name: KLUSTAIR_LIMITDATE
                value: {{ .Values.klustairJob.limitNR | quote}}
              {{ end -}}
              {{ if .Values.trivy.registryToken -}}
              - name: TRIVY_REDGISTRY_TOKEN
                value: {{ .Values.trivy.registryToken | quote}}
              {{ end }}
            volumeMounts:
              - name: configs
                mountPath: "/etc/klustair"
                readOnly: true
            resources:
              {{- toYaml .Values.klustairJob.resources | nindent 14 }}
          volumes:
            - name: configs
              secret:
                  secretName: {{ include "klustair.fullname" . }}-configs
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.klustairJob.serviceAccount.create }}
          serviceAccountName: {{ template "klustair.jobServiceAccountName" . }}
        {{- end }}
{{- end }}
