{{- if .Values.klustair-runner.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: {{ .Values.klustair-runner.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: klustair-runner
            image: {{ .Values.klustair.image }}:{{ .Values.klustair.tag }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            command: ["runner.py", "--verbose", "--namespacesblacklist", "{{ .Values.klustair-runner.namespaceblacklist }}"]
            env:
              - name: ANCHORE_CLI_USER
                value: "admin"
              - name: ANCHORE_CLI_PASS
                value: {{ index .Values "anchore-engine" "anchoreGlobal" "defaultAdminPassword" }}
              - name: ANCHORE_CLI_URL
                value: {{ .Values.klustair.AnchoreCliUrl }}
              - name: KUBECONFIG
                value: /configs/kube.config
              - name: DB_HOST
                value: {{ .Release.Name }}-postgresql
              - name: DB_DATABASE
                value: {{ index .Values "anchore-engine" "postgresql" "postgresDatabase" }}
              - name: DB_USERNAME
                value: {{ index .Values "anchore-engine" "postgresql" "postgresUser" }}
              - name: DB_PASSWORD
                value: {{ index .Values "anchore-engine" "postgresql" "postgresPassword" }}
            volumeMounts:
              - name: kubeconfig
                mountPath: "/configs"
                readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: kubeconfig
            secret:
                secretName: {{ .Release.Name }}-kubeconfig
{{- end }}
